import os
import re

files_to_update = [
    'backend/src/features/platformCrm/enquiry.listeners.js',
    'backend/src/features/platformInvoice/platformInvoice.service.js',
    'backend/src/features/platformPayment/platformPayment.service.js',
    'backend/src/features/platformQuote/platformQuote.service.js',
    'backend/src/routes/public.routes.js',
    'frontend/src/features/auth/views/Login.jsx',
    'frontend/src/features/billing/components/PaymentCheckoutModal.jsx',
    'frontend/src/features/billing/utils/invoiceTemplate.js',
    'frontend/src/features/platformBilling/components/tabs/PaymentTab.jsx',
    'frontend/src/layout/Sidebar.jsx',
    'frontend/src/views/pages/billing/BillingInvoiceLinkPage.jsx',
    'frontend/src/views/pages/contact/ContactSupportPage.jsx',
    'frontend/src/views/pages/deleteAccount/DeleteAccountPage.jsx',
    'frontend/src/views/pages/invite/InviteHandler.jsx',
    'frontend/src/views/pages/pay/PublicCheckoutPage.jsx',
    'frontend/src/views/pages/privacyPolicy/PrivacyPolicyPage.jsx',
    'frontend/src/views/pages/terms/TermsPage.jsx',
    'mobile/mobile-app/app.json',
    'mobile/mobile-app/app/(auth)/register.tsx',
    'mobile/mobile-app/app/(resident)/settings/index.tsx',
    'mobile/mobile-app/app/_layout.tsx',
    'mobile/mobile-app/components/feedback/ErrorBanner.tsx',
    'mobile/mobile-app/components/ui/ScreenShell.tsx',
    'mobile/mobile-app/src/features/auth/components/MicrosoftSignInButton.tsx',
    'mobile/mobile-app/src/features/billing/utils/invoicePdfUtility.ts',
    'mobile/mobile-app/src/features/noticeBoard/components/PollPostCard.tsx',
    'mobile/mobile-app/src/features/profile/data/locationData.ts',
    'mobile/mobile-app/src/utils/appBarcodeProtocol.ts',
    'mobile/mobile-app/src/utils/i18n/ar.ts',
    'mobile/mobile-app/src/utils/i18n/en.ts',
    'mobile/mobile-app/src/utils/i18n/hi.ts',
    'mobile/mobile-app/src/utils/i18n/kn.ts',
    'mobile/mobile-app/src/utils/i18n/ml.ts',
    'mobile/mobile-app/src/utils/i18n/ta.ts',
    'mobile/mobile-app/src/utils/i18n/te.ts',
    'backend/public/privacy-policy.html'
]

replacements = [
    # General user-facing replacements
    (r'ManageMyGate Platform', 'Nahom Platform'),
    (r'ManageMyGate Backend API', 'Nahom Backend API'),
    (r'ManageMyGate Team', 'Nahom Team'),
    (r'Your ManageMyGate Enquiry', 'Your Nahom Enquiry'),
    (r'"ManageMyGate"', '"Nahom"'),
    (r'\'ManageMyGate\'', '\'Nahom\''),
    (r'>ManageMyGate<', '>Nahom<'),
    (r'ManageMyGate Authorized Financial Invoice', 'Nahom Authorized Financial Invoice'),
    (r'ManageMyGate@2026', 'Nahom@2026'),
    
    # Emails
    (r'support@managemygate\.com', 'support@nahom.com'),
    (r'developer@managemygate\.com', 'developer@nahom.com'),
    (r'admin@managemygate\.com', 'admin@nahom.com'),
    (r'user@managemygate\.com', 'user@nahom.com'),
    (r'onboarding@resend\.dev', 'onboarding@resend.dev'), # just in case
    (r'ManageMyGate <onboarding@resend\.dev>', 'Nahom <onboarding@resend.dev>'),

    # Websites in text
    (r'support\.managemygate\.com', 'support.nahom.com'),
    
    # Mobile Specific
    (r'Welcome to Manage-My-Gate!', 'Welcome to Nahom!'),
    (r'Manage-My-Gate Visitor Pass', 'Nahom Visitor Pass'),
    (r'generated by Manage-My-Gate', 'generated by Nahom'),
    (r'Manage My Gate', 'Nahom'),
    (r'Manage-My-Gate App', 'Nahom App'),
    (r'Manage-My-Gate Application', 'Nahom Application'),
    (r'Manage-My-Gate', 'Nahom'), # general Catch-all for hyphenated
    
    # Non-English i18n Values (keeping the key the same)
    (r"'مانيج ماي جيت'", "'ناهوم'"),
    (r"'مرحباً بك في مانيج ماي جيت!'", "'مرحباً بك في ناهوم!'"),
    (r"'تصريح زائر مانيج ماي جيت'", "'تصريح زائر ناهوم'"),
    (r"التي تم إنشاؤها بواسطة Manage-My-Gate", "التي تم إنشاؤها بواسطة ناهوم"),
    (r"'मैनेज माय प्रवेश द्वार'", "'नाहोम'"),
    (r"'मैनेज-माई-गेट में आपका स्वागत है!'", "'नाहोम में आपका स्वागत है!'"),
    (r"'मैनेज-माई-गेट विज़िटर पास'", "'नाहोम विज़िटर पास'"),
    (r"Manage-My-Gate द्वारा जनरेट किए गए पास", "नाहोम द्वारा जनरेट किए गए पास"),
    (r"'ಮ್ಯಾನೇಜ್ ಮೈ ಗೇಟ್'", "'ನಹೋಮ್'"),
    (r"'Manage-My-Gate ಗೆ ಸುಸ್ವಾಗತ!'", "'ನಹೋಮ್ ಗೆ ಸುಸ್ವಾಗತ!'"),
    (r"'Manage-My-Gate ಸಂದರ್ಶಕರ ಪಾಸ್'", "'ನಹೋಮ್ ಸಂದರ್ಶಕರ ಪಾಸ್'"),
    (r"Manage-My-Gate ರಚಿಸಿದ ಪಾಸ್‌ಗಳು", "ನಹೋಮ್ ರಚಿಸಿದ ಪಾಸ್‌ಗಳು"),
    (r"'മാനേജ് മൈ ഗേറ്റ്'", "'നഹോം'"),
    (r"'മാനേജ്-മൈ-ഗേറ്റിലേക്ക് സ്വാഗതം!'", "'നഹോമിലേക്ക് സ്വാഗതം!'"),
    (r"'മാനേജ്-മൈ-ഗേറ്റ് സന്ദർശക പാസ്'", "'നഹോം സന്ദർശക പാസ്'"),
    (r"Manage-My-Gate സൃഷ്ടിച്ച പാസുകൾ", "നഹോം സൃഷ്ടിച്ച പാസുകൾ"),
    (r"'மேனேஜ் மை நுழைவாயில்'", "'நஹோம்'"),
    (r"'Manage-My-Gate-க்கு வரவேற்கிறோம்!'", "'நஹோம்-க்கு வரவேற்கிறோம்!'"),
    (r"'Manage-My-Gate பார்வையாளர் பாஸ்'", "'நஹோம் பார்வையாளர் பாஸ்'"),
    (r"Manage-My-Gate மூலம் உருவாக்கப்பட்ட பாஸ்கள்", "நஹோம் மூலம் உருவாக்கப்பட்ட பாஸ்கள்"),
    (r"'మేనేజ్ మై గేట్'", "'నహోమ్'"),
    (r"'Manage-My-Gate కు స్వాగతం!'", "'నహోమ్ కు స్వాగతం!'"),
    (r"'Manage-My-Gate సందర్శకుల పాస్'", "'నహోమ్ సందర్శకుల పాస్'"),
    (r"Manage-My-Gate రూపొందించిన పాస్‌లు", "నహోమ్ రూపొందించిన పాస్‌లు"),
]

for file_path in files_to_update:
    if not os.path.exists(file_path):
        continue
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    new_content = content
    for pattern, replacement in replacements:
        new_content = re.sub(pattern, replacement, new_content)
    
    # Catch raw "ManageMyGate" but avoid API URLs
    # Since we can't easily regex negative lookbehind for URLs, we replace specific occurrences
    new_content = re.sub(r'(?<!\.)ManageMyGate(?!\.com)', 'Nahom', new_content)
    
    if content != new_content:
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(new_content)
        print(f"Updated {file_path}")
