import React, { useState, useEffect } from 'react';
import {
  View,
  Modal,
  TouchableOpacity,
  TextInput,
  StatusBar,
} from 'react-native';
import { Text } from '@/components/ui/text';
import { Button } from '@/components/ui/button';
import {
  ChevronLeft,
  Camera,
  CameraOff,
  Zap,
  ZapOff,
  KeyRound,
  CheckCircle2,
  ShieldCheck,
  AlertTriangle,
} from 'lucide-react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { QRScannerOverlay } from '@/components/hardware/QRScannerOverlay';
import {
  parseAndValidateAppBarcode,
  encodeAppBarcode,
  AppBarcodeType,
} from '@/src/utils/appBarcodeProtocol';

export interface GuardQRScannerModalProps {
  visible: boolean;
  onClose: () => void;
  onScanCode: (code: string) => void;
  title?: string;
  instruction?: string;
}

const INVITATION_SIM_TYPES: { type: AppBarcodeType; label: string; code: string; visitorName: string }[] = [
  { type: 'GUEST', label: 'Guest Pass', code: '849201', visitorName: 'Sarah Jenkins' },
  { type: 'GROUP', label: 'Group Visit', code: '849202', visitorName: 'Smith Family' },
  { type: 'CAB', label: 'Cab / Auto', code: '849203', visitorName: 'Ahmed Khan (Uber)' },
  { type: 'DELIVERY', label: 'Delivery', code: '849204', visitorName: 'Mohammad Al-Hassan (Amazon)' },
  { type: 'SERVICE', label: 'Service / Staff', code: '849205', visitorName: 'Ravi Kumar (Electrician)' },
];

export const GuardQRScannerModal: React.FC<GuardQRScannerModalProps> = ({
  visible,
  onClose,
  onScanCode,
  title = 'Guard Gate QR Scanner',
  instruction,
}) => {
  const insets = useSafeAreaInsets();
  const [permission, requestPermission] = useCameraPermissions();
  const [scanned, setScanned] = useState(false);
  const [torchOn, setTorchOn] = useState(false);
  const [scannerMode, setScannerMode] = useState<'barcode' | 'qr'>('barcode');
  const [manualCode, setManualCode] = useState('');
  const [validationError, setValidationError] = useState<string | null>(null);
  const [simIndex, setSimIndex] = useState(0);

  // Reset state on open/close
  useEffect(() => {
    if (visible) {
      setScanned(false);
      setTorchOn(false);
      setManualCode('');
      setValidationError(null);
    } else {
      setTorchOn(false);
      setValidationError(null);
    }
    return () => {
      setTorchOn(false);
    };
  }, [visible]);

  const handleBarcodeScanned = ({ data }: { data: string }) => {
    if (scanned || !data) return;

    // Strictly validate barcode against Manage-My-Gate protocol
    const validation = parseAndValidateAppBarcode(data);
    if (!validation.isValid) {
      setValidationError(
        validation.errorMessage ||
          'Unrecognized Barcode: Only passes generated by Manage-My-Gate are accepted.'
      );
      setTimeout(() => {
        setValidationError(null);
      }, 3500);
      return;
    }

    setScanned(true);
    setTorchOn(false);
    setValidationError(null);
    onScanCode(data.trim());
    onClose();
  };

  const handleManualScan = () => {
    const raw = manualCode.trim();
    if (!raw) return;

    const validation = parseAndValidateAppBarcode(raw);
    if (!validation.isValid) {
      setValidationError(
        validation.errorMessage ||
          'Invalid Code: Enter a valid 6-digit PIN or MMG pass token.'
      );
      setTimeout(() => {
        setValidationError(null);
      }, 3500);
      return;
    }

    setTorchOn(false);
    setValidationError(null);
    onScanCode(validation.code || raw);
    setManualCode('');
    onClose();
  };

  const handleSimulatePass = () => {
    const item = INVITATION_SIM_TYPES[simIndex % INVITATION_SIM_TYPES.length];
    setSimIndex((prev) => prev + 1);

    const simulatedBarcode = encodeAppBarcode(item.type, item.code, undefined, item.visitorName);
    setTorchOn(false);
    setValidationError(null);
    onScanCode(simulatedBarcode);
    onClose();
  };

  const nextSimItem = INVITATION_SIM_TYPES[simIndex % INVITATION_SIM_TYPES.length];

  return (
    <Modal
      visible={visible}
      animationType="slide"
      presentationStyle="fullScreen"
      statusBarTranslucent
      onRequestClose={onClose}
    >
      <StatusBar barStyle="light-content" backgroundColor="#000000" />
      <View className="flex-1 bg-black relative">
        {/* 1. Fullscreen Live Camera Viewport */}
        {!permission ? (
          <View className="flex-1 bg-black items-center justify-center p-4">
            <Text className="text-white text-xs font-semibold">
              Initializing camera hardware...
            </Text>
          </View>
        ) : !permission.granted ? (
          <View className="flex-1 bg-black items-center justify-center p-6 gap-3">
            <View className="w-16 h-16 rounded-full bg-white/10 items-center justify-center mb-1">
              <CameraOff size={32} color="#ffffff" />
            </View>
            <Text className="text-white text-base font-bold text-center">
              Camera Permission Required
            </Text>
            <Text className="text-white/70 text-xs text-center px-6 mb-2">
              Camera access is required to scan and verify visitor QR passes at the gate.
            </Text>
            <Button
              variant="default"
              onPress={requestPermission}
              className="bg-primary px-6 py-2.5 rounded-xl"
            >
              <View className="flex-row items-center gap-2">
                <Camera size={16} color="#ffffff" />
                <Text className="text-white text-xs font-bold">Grant Camera Permission</Text>
              </View>
            </Button>
          </View>
        ) : (
          <View className="flex-1 w-full h-full bg-black relative">
            <CameraView
              facing="back"
              enableTorch={Boolean(torchOn)}
              barcodeScannerSettings={{
                barcodeTypes: ['qr', 'code128', 'code39', 'ean13', 'ean8', 'pdf417', 'upc_a', 'upc_e'],
              }}
              onBarcodeScanned={scanned ? undefined : handleBarcodeScanned}
              style={{ width: '100%', height: '100%' }}
            />
            <QRScannerOverlay
              mode={scannerMode}
              instruction={
                scannerMode === 'barcode'
                  ? 'Fit Barcode inside Bright Viewport'
                  : 'Align Visitor Pass QR inside Bright Viewport'
              }
            />
          </View>
        )}

        {/* 2. Top Navigation Bar (High-Tech Floating HUD) */}
        <View
          className="absolute top-0 left-0 right-0 z-50 px-4"
          style={{ paddingTop: Math.max(insets.top, 16) + 6 }}
          pointerEvents="box-none"
        >
          <View className="flex-row items-center justify-between" pointerEvents="box-none">
            {/* Circular Frosted Dismiss Button */}
            <TouchableOpacity
              activeOpacity={0.7}
              hitSlop={{ top: 20, bottom: 20, left: 20, right: 20 }}
              onPress={onClose}
              className="h-11 w-11 rounded-full bg-black/80 border border-white/30 items-center justify-center shadow-xl active:bg-black"
              accessibilityRole="button"
              accessibilityLabel="Close scanner"
            >
              <ChevronLeft size={24} color="#FFFFFF" strokeWidth={2.5} />
            </TouchableOpacity>

            {/* Mode Switcher: Barcode Scanner vs QR */}
            <View className="bg-black/90 border border-white/30 rounded-full p-1 flex-row items-center shadow-xl">
              <TouchableOpacity
                onPress={() => setScannerMode('barcode')}
                className={`px-3 py-1.5 rounded-full flex-row items-center gap-1.5 ${
                  scannerMode === 'barcode' ? 'bg-emerald-500' : 'bg-transparent'
                }`}
              >
                <Text
                  className={`text-[11px] font-bold uppercase tracking-wider ${
                    scannerMode === 'barcode' ? 'text-black font-black' : 'text-white/80'
                  }`}
                >
                  Barcode
                </Text>
              </TouchableOpacity>
              <TouchableOpacity
                onPress={() => setScannerMode('qr')}
                className={`px-3 py-1.5 rounded-full flex-row items-center gap-1.5 ${
                  scannerMode === 'qr' ? 'bg-emerald-500' : 'bg-transparent'
                }`}
              >
                <Text
                  className={`text-[11px] font-bold uppercase tracking-wider ${
                    scannerMode === 'qr' ? 'text-black font-black' : 'text-white/80'
                  }`}
                >
                  QR Code
                </Text>
              </TouchableOpacity>
            </View>

            {/* Flashlight Torch Toggle Capsule */}
            <TouchableOpacity
              activeOpacity={0.8}
              onPress={() => setTorchOn((prev) => !prev)}
              className={`px-3 py-1.5 rounded-full flex-row items-center gap-1.5 border shadow-lg ${
                torchOn
                  ? 'bg-amber-400 border-amber-300 shadow-amber-500/40'
                  : 'bg-black/80 border-white/30 shadow-black/50'
              }`}
              accessibilityRole="button"
              accessibilityLabel={torchOn ? 'Turn flashlight off' : 'Turn flashlight on'}
            >
              {torchOn ? (
                <>
                  <Zap size={14} color="#000000" fill="#000000" strokeWidth={2.5} />
                  <Text className="text-[11px] font-black text-black tracking-wider uppercase">
                    Light ON
                  </Text>
                </>
              ) : (
                <>
                  <ZapOff size={14} color="#ffffff" strokeWidth={2.5} />
                  <Text className="text-[11px] font-bold text-white tracking-wider uppercase">
                    Light
                  </Text>
                </>
              )}
            </TouchableOpacity>
          </View>

          {/* Floating High-Visibility Rejection Banner */}
          {validationError && (
            <View className="mt-3 bg-rose-600/95 border border-rose-400 p-3 rounded-2xl flex-row items-center gap-2.5 shadow-2xl">
              <AlertTriangle size={18} color="#ffffff" />
              <Text className="text-xs font-bold text-white flex-1 leading-snug">
                {validationError}
              </Text>
            </View>
          )}
        </View>

        {/* 3. Bottom Floating Control Console */}
        <View
          className="absolute bottom-0 left-0 right-0 z-50 p-4 items-center"
          style={{ paddingBottom: Math.max(insets.bottom, 16) + 6 }}
          pointerEvents="box-none"
        >
          <View
            className="w-full max-w-md bg-black/85 border border-white/20 rounded-3xl p-3.5 gap-3 shadow-2xl"
            pointerEvents="auto"
          >
            <Text className="text-[11px] font-semibold text-white/70 text-center tracking-wide">
              Scan pass QR or enter 6-digit keycode
            </Text>

            {/* Manual Pass PIN Strip */}
            <View className="flex-row items-center gap-2">
              <View className="flex-1 flex-row items-center gap-2 bg-white/10 border border-white/20 rounded-2xl px-3 h-12">
                <KeyRound size={15} color="#94a3b8" />
                <TextInput
                  value={manualCode}
                  onChangeText={setManualCode}
                  placeholder="Enter 6-digit PIN..."
                  placeholderTextColor="#94a3b8"
                  keyboardType="default"
                  autoCapitalize="characters"
                  className="flex-1 text-white text-xs font-mono font-bold"
                  onSubmitEditing={handleManualScan}
                  returnKeyType="go"
                />
              </View>

              <TouchableOpacity
                activeOpacity={0.8}
                onPress={handleManualScan}
                className="h-12 px-4 rounded-2xl bg-emerald-600 active:bg-emerald-700 flex-row items-center justify-center gap-1.5 shadow-md"
                accessibilityRole="button"
                accessibilityLabel="Verify manual passcode"
              >
                <CheckCircle2 size={16} color="#ffffff" strokeWidth={2.5} />
                <Text className="text-xs font-bold text-white">Verify</Text>
              </TouchableOpacity>
            </View>

            {/* Action Chips Row */}
            <View className="flex-row items-center justify-between pt-1">
              <TouchableOpacity
                activeOpacity={0.8}
                onPress={handleSimulatePass}
                className="bg-black/70 border border-white/25 px-3 py-1.5 rounded-full flex-row items-center gap-1.5"
              >
                <Camera size={13} color="#ffffff" />
                <Text className="text-[11px] font-semibold text-white/90">
                  Simulate: {nextSimItem.label}
                </Text>
              </TouchableOpacity>

              <TouchableOpacity
                activeOpacity={0.8}
                onPress={onClose}
                className="bg-black/70 border border-white/25 px-3 py-1.5 rounded-full flex-row items-center gap-1.5"
              >
                <Text className="text-[11px] font-semibold text-white/90">
                  Close Scanner
                </Text>
              </TouchableOpacity>
            </View>
          </View>
        </View>
      </View>
    </Modal>
  );
};

export default GuardQRScannerModal;
