import mongoose from 'mongoose';

const pricingDetailsSchema = new mongoose.Schema({
  baseAmount: { type: Number, default: 0 },
  taxAmount: { type: Number, default: 0 },
  discountAmount: { type: Number, default: 0 },
  securityDeposit: { type: Number, default: 0 },
  totalAmount: { type: Number, default: 0 },
  refundAmount: { type: Number, default: 0 },
  cancellationCharge: { type: Number, default: 0 }
}, { _id: false });

const amenityBookingSchema = new mongoose.Schema({
  orgId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Organization',
    required: [true, 'Organization ID is required'],
    index: true
  },
  amenityId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Amenity',
    required: [true, 'Amenity ID is required']
  },
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'User ID is required']
  },
  bookingDate: {
    type: String,
    required: [true, 'Booking date is required'],
    match: [/^\d{4}-\d{2}-\d{2}$/, 'Please provide a valid date format (YYYY-MM-DD)']
  },
  startTime: {
    type: String,
    required: [true, 'Start time is required'],
    match: [/^([01]\d|2[0-3]):?([0-5]\d)$/, 'Please provide a valid time format (HH:MM)']
  },
  endTime: {
    type: String,
    required: [true, 'End time is required'],
    match: [/^([01]\d|2[0-3]):?([0-5]\d)$/, 'Please provide a valid time format (HH:MM)']
  },
  status: {
    type: String,
    enum: ['pending', 'approved', 'rejected', 'cancelled', 'confirmed', 'checked-in', 'completed'],
    default: 'pending'
  },
  
  // Pricing & Payment
  pricingDetails: {
    type: pricingDetailsSchema,
    default: () => ({})
  },
  paymentStatus: {
    type: String,
    enum: ['pending', 'processing', 'success', 'failed', 'cancelled', 'refunded', 'partial_refund'],
    default: 'pending'
  },
  paymentId: {
    type: String, // ID generated by MockPaymentProvider or Stripe
    default: null
  },
  paymentMethod: {
    type: String,
    default: 'None'
  },

  bookingId: {
    type: String,
    unique: true,
    sparse: true
  },
  // QR Access
  qrCode: {
    type: String, // The encrypted payload or URL to the QR image
    default: null
  },
  qrStatus: {
    type: String,
    enum: ['active', 'expired', 'revoked'],
    default: 'active'
  },
  qrGeneratedAt: {
    type: Date,
    default: null
  },
  qrExpiresAt: {
    type: Date,
    default: null
  },

  // Lifecycle
  checkInTime: {
    type: Date,
    default: null
  },
  checkOutTime: {
    type: Date,
    default: null
  },
  cancellationReason: {
    type: String,
    default: null
  },
  refundPercentage: {
    type: Number,
    default: 0
  },
  cancelledAt: {
    type: Date,
    default: null
  },
  cancelledBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },
  
  // Review/Approval
  reviewedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },
  reviewedAt: {
    type: Date,
    default: null
  },
  rejectionReason: {
    type: String,
    default: null
  }
}, { timestamps: true });

// Prevent exact overlap checking via indexes? Actually better done in application logic.
// We can index by orgId and amenityId for faster queries
amenityBookingSchema.index({ orgId: 1, amenityId: 1, bookingDate: 1 });
amenityBookingSchema.index({ userId: 1, orgId: 1 });

export default mongoose.model('AmenityBooking', amenityBookingSchema);
