import React, { useState, useEffect, useCallback } from 'react';
import { View, TouchableOpacity, TextInput } from 'react-native';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import {
  Camera,
  CameraOff,
  ChevronLeft,
  History,
  Zap,
  ZapOff,
  Building2,
  KeyRound,
  CheckCircle2,
  AlertTriangle,
} from 'lucide-react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { QRScannerOverlay } from '@/components/hardware/QRScannerOverlay';
import { ScanResultSheet, type ScanResultData } from '@/components/hardware/ScanResultSheet';
import { BottomSheet, Button, ListCard, Text } from '@/components/ui';
import { EmptyState } from '@/components/feedback';
import { useSecurityScanner } from '@/src/features/amenities/hooks/useSecurityScanner';
import { parseAndValidateAppBarcode } from '@/src/utils/appBarcodeProtocol';

export default function AmenitySecurityGateScannerScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const [permission, requestPermission] = useCameraPermissions();

  const [torchOn, setTorchOn] = useState(false);
  const [scannerMode, setScannerMode] = useState<'barcode' | 'qr'>('barcode');
  const [manualCode, setManualCode] = useState('');
  const [isHistorySheetOpen, setIsHistorySheetOpen] = useState(false);
  const [hasScannedCooldown, setHasScannedCooldown] = useState(false);
  const [customRejection, setCustomRejection] = useState<{ title: string; message: string } | null>(null);

  const {
    isScanning,
    isResultModalOpen,
    checkInResult,
    checkingIn,
    recentScans,
    handleBarCodeScanned,
    resetScanner,
  } = useSecurityScanner();

  // Reset torch on unmount or when modal opens
  useEffect(() => {
    return () => {
      setTorchOn(false);
    };
  }, []);

  useEffect(() => {
    if (isResultModalOpen || customRejection) {
      setTorchOn(false);
    }
  }, [isResultModalOpen, customRejection]);

  const handleGoBack = () => {
    setTorchOn(false);
    if (router.canGoBack()) {
      router.back();
    } else {
      router.replace('/(resident)/amenities/dashboard' as any);
    }
  };

  const handleCameraScanned = ({ data }: { data: string }) => {
    if (hasScannedCooldown || !isScanning || !data) return;
    setHasScannedCooldown(true);
    setTorchOn(false);

    // Strictly validate barcode against Manage-My-Gate application signature
    const validation = parseAndValidateAppBarcode(data);
    if (!validation.isValid) {
      setCustomRejection({
        title: 'Unrecognized Barcode',
        message:
          validation.errorMessage ||
          'This barcode was not generated by Manage-My-Gate. Facility access refused.',
      });
      setTimeout(() => {
        setHasScannedCooldown(false);
      }, 2500);
      return;
    }

    const targetCode = validation.code || validation.passId || data.trim();
    handleBarCodeScanned({ type: 'CAMERA', data: targetCode });

    // Cooldown prevents burst duplicate detections
    setTimeout(() => {
      setHasScannedCooldown(false);
    }, 2500);
  };

  const handleManualSubmit = () => {
    const raw = manualCode.trim();
    if (!raw || checkingIn) return;
    setTorchOn(false);

    const validation = parseAndValidateAppBarcode(raw);
    if (!validation.isValid) {
      setCustomRejection({
        title: 'Unrecognized Code',
        message:
          validation.errorMessage ||
          'Enter a valid 6-digit PIN or MMG pass token.',
      });
      return;
    }

    const targetCode = validation.code || validation.passId || raw;
    handleBarCodeScanned({ type: 'MANUAL', data: targetCode });
    setManualCode('');
  };

  const handleSimulateScan = () => {
    setTorchOn(false);
    setCustomRejection(null);
    handleBarCodeScanned({
      type: 'SIMULATION',
      data: 'MMG:AMENITY:BK-778899',
    });
  };

  const handleDismissResult = () => {
    resetScanner();
    setCustomRejection(null);
    setHasScannedCooldown(false);
  };

  // Standardize check-in result for ScanResultSheet
  const formattedResult: ScanResultData | null = customRejection
    ? {
        success: false,
        status: 'REJECTED',
        title: customRejection.title,
        message: customRejection.message,
        visitorName: 'External Barcode',
        passType: 'UNAUTHORIZED SCAN',
        amenityName: 'Access Denied',
        bookingReference: 'NOT_MMG_PASS',
      }
    : checkInResult
    ? {
        success: Boolean(checkInResult.success),
        status: checkInResult.success ? 'VERIFIED' : 'REJECTED',
        title: checkInResult.success
          ? 'Amenity Ticket Verified'
          : 'Amenity Access Refused',
        message:
          checkInResult.message ||
          (checkInResult.success
            ? 'Reservation pass is active and verified for entry.'
            : 'Pass is expired, invalid, or already checked in.'),
        visitorName: checkInResult.booking?.residentName || 'Resident Member',
        passType: 'AMENITY ACCESS',
        amenityName: checkInResult.booking?.amenityName || 'Community Facility',
        unitOrVilla:
          (checkInResult.booking as any)?.unitNumber ||
          (checkInResult.booking as any)?.villaNumber ||
          (checkInResult.booking as any)?.unit,
        validityWindow:
          checkInResult.booking?.startTime && checkInResult.booking?.endTime
            ? `${checkInResult.booking.startTime} - ${checkInResult.booking.endTime}`
            : undefined,
        bookingReference:
          checkInResult.booking?.bookingId ||
          (checkInResult.booking as any)?.bookingReference ||
          checkInResult.booking?._id ||
          checkInResult.booking?.passCode ||
          'N/A',
      }
    : null;

  return (
    <View className="flex-1 bg-black relative">
      {/* 1. Camera Viewport */}
      {!permission ? (
        <View className="flex-1 bg-black items-center justify-center p-4">
          <Text className="text-white text-xs font-semibold">Initializing camera hardware...</Text>
        </View>
      ) : !permission.granted ? (
        <View className="flex-1 bg-black items-center justify-center p-6 gap-3">
          <View className="w-16 h-16 rounded-full bg-white/10 items-center justify-center mb-1">
            <CameraOff size={32} color="#ffffff" />
          </View>
          <Text className="text-white text-base font-bold text-center">
            Camera Permission Required
          </Text>
          <Text className="text-white/70 text-xs text-center px-6 mb-2">
            Camera access is required to scan facility reservation QR passes.
          </Text>
          <Button
            variant="default"
            onPress={requestPermission}
            className="bg-primary px-6 py-2.5 rounded-xl"
          >
            <View className="flex-row items-center gap-2">
              <Camera size={16} color="#ffffff" />
              <Text className="text-white text-xs font-bold">Grant Camera Permission</Text>
            </View>
          </Button>
        </View>
      ) : (
          <View className="flex-1 w-full h-full bg-black relative">
            <CameraView
              facing="back"
              enableTorch={Boolean(torchOn)}
              barcodeScannerSettings={{
                barcodeTypes: ['qr', 'code128', 'code39', 'ean13', 'ean8', 'pdf417', 'upc_a', 'upc_e'],
              }}
              onBarcodeScanned={isScanning && !hasScannedCooldown ? handleCameraScanned : undefined}
              style={{ width: '100%', height: '100%' }}
            />
            <QRScannerOverlay
              mode={scannerMode}
              instruction={
                scannerMode === 'barcode'
                  ? 'Fit Barcode inside Bright Viewport'
                  : 'Align Amenity Reservation QR inside Bright Viewport'
              }
            />
          </View>
        )}

      {/* 2. Top Navigation Bar (High-Tech Floating HUD) */}
      <View
        className="absolute top-0 left-0 right-0 z-50 px-4"
        style={{ paddingTop: Math.max(insets.top, 16) + 6 }}
        pointerEvents="box-none"
      >
        <View className="flex-row items-center justify-between" pointerEvents="box-none">
          {/* Prominent High-Visibility Back Button */}
          <TouchableOpacity
            activeOpacity={0.7}
            hitSlop={{ top: 20, bottom: 20, left: 20, right: 20 }}
            onPress={handleGoBack}
            className="h-11 w-11 rounded-full bg-black/80 border border-white/30 items-center justify-center shadow-xl active:bg-black"
            accessibilityRole="button"
            accessibilityLabel="Go back"
          >
            <ChevronLeft size={24} color="#FFFFFF" strokeWidth={2.5} />
          </TouchableOpacity>

          {/* Mode Switcher: Barcode Scanner vs QR */}
          <View className="bg-black/90 border border-white/30 rounded-full p-1 flex-row items-center shadow-xl">
            <TouchableOpacity
              onPress={() => setScannerMode('barcode')}
              className={`px-3 py-1.5 rounded-full flex-row items-center gap-1.5 ${
                scannerMode === 'barcode' ? 'bg-emerald-500' : 'bg-transparent'
              }`}
            >
              <Text
                className={`text-[11px] font-bold uppercase tracking-wider ${
                  scannerMode === 'barcode' ? 'text-black font-black' : 'text-white/80'
                }`}
              >
                Barcode
              </Text>
            </TouchableOpacity>
            <TouchableOpacity
              onPress={() => setScannerMode('qr')}
              className={`px-3 py-1.5 rounded-full flex-row items-center gap-1.5 ${
                scannerMode === 'qr' ? 'bg-emerald-500' : 'bg-transparent'
              }`}
            >
              <Text
                className={`text-[11px] font-bold uppercase tracking-wider ${
                  scannerMode === 'qr' ? 'text-black font-black' : 'text-white/80'
                }`}
              >
                QR Code
              </Text>
            </TouchableOpacity>
          </View>

          {/* Flashlight Torch Toggle Capsule */}
          <TouchableOpacity
            activeOpacity={0.8}
            onPress={() => setTorchOn((prev) => !prev)}
            className={`px-3 py-1.5 rounded-full flex-row items-center gap-1.5 border shadow-lg ${
              torchOn
                ? 'bg-amber-400 border-amber-300 shadow-amber-500/40'
                : 'bg-black/80 border-white/30 shadow-black/50'
            }`}
            accessibilityRole="button"
            accessibilityLabel={torchOn ? 'Turn flashlight off' : 'Turn flashlight on'}
          >
            {torchOn ? (
              <>
                <Zap size={14} color="#000000" fill="#000000" strokeWidth={2.5} />
                <Text className="text-[11px] font-black text-black tracking-wider uppercase">
                  Light ON
                </Text>
              </>
            ) : (
              <>
                <ZapOff size={14} color="#ffffff" strokeWidth={2.5} />
                <Text className="text-[11px] font-bold text-white tracking-wider uppercase">
                  Light
                </Text>
              </>
            )}
          </TouchableOpacity>
        </View>

        {/* Floating High-Visibility Rejection Banner */}
        {customRejection && (
          <View className="mt-3 bg-rose-600/95 border border-rose-400 p-3 rounded-2xl flex-row items-center gap-2.5 shadow-2xl">
            <AlertTriangle size={18} color="#ffffff" />
            <Text className="text-xs font-bold text-white flex-1 leading-snug">
              {customRejection.message}
            </Text>
          </View>
        )}
      </View>

      {/* 3. Bottom Floating Control Console */}
      <View
        className="absolute bottom-0 left-0 right-0 z-50 p-4 items-center"
        style={{ paddingBottom: Math.max(insets.bottom, 16) + 6 }}
        pointerEvents="box-none"
      >
        <View
          className="w-full max-w-md bg-black/85 border border-white/20 rounded-3xl p-3.5 gap-3 shadow-2xl"
          pointerEvents="auto"
        >
          <Text className="text-[11px] font-semibold text-white/70 text-center tracking-wide">
            Scan pass QR or enter booking reference keycode
          </Text>

          {/* Manual Pass PIN Strip */}
          <View className="flex-row items-center gap-2">
            <View className="flex-1 flex-row items-center gap-2 bg-white/10 border border-white/20 rounded-2xl px-3 h-12">
              <KeyRound size={15} color="#94a3b8" />
              <TextInput
                value={manualCode}
                onChangeText={setManualCode}
                placeholder="Enter booking PIN or code..."
                placeholderTextColor="#94a3b8"
                autoCapitalize="characters"
                className="flex-1 text-white text-xs font-mono font-bold"
                onSubmitEditing={handleManualSubmit}
                returnKeyType="go"
              />
            </View>

            <TouchableOpacity
              activeOpacity={0.8}
              onPress={handleManualSubmit}
              disabled={checkingIn || !manualCode.trim()}
              className="h-12 px-4 rounded-2xl bg-emerald-600 active:bg-emerald-700 flex-row items-center justify-center gap-1.5 shadow-md"
              accessibilityRole="button"
              accessibilityLabel="Verify manual passcode"
            >
              <CheckCircle2 size={16} color="#ffffff" strokeWidth={2.5} />
              <Text className="text-xs font-bold text-white">
                {checkingIn ? 'Verifying...' : 'Verify'}
              </Text>
            </TouchableOpacity>
          </View>

          {/* Action Chips Row */}
          <View className="flex-row items-center justify-between pt-1">
            <TouchableOpacity
              activeOpacity={0.8}
              onPress={handleSimulateScan}
              disabled={checkingIn}
              className="bg-black/70 border border-white/25 px-3 py-1.5 rounded-full flex-row items-center gap-1.5"
            >
              <Camera size={13} color="#ffffff" />
              <Text className="text-[11px] font-semibold text-white/90">
                {checkingIn ? 'Simulating...' : 'Simulate Test Scan'}
              </Text>
            </TouchableOpacity>

            <TouchableOpacity
              activeOpacity={0.8}
              onPress={() => setIsHistorySheetOpen(true)}
              className="bg-black/70 border border-white/25 px-3 py-1.5 rounded-full flex-row items-center gap-1.5"
            >
              <History size={13} color="#ffffff" />
              <Text className="text-[11px] font-semibold text-white/90">
                Today's Logs ({recentScans.length})
              </Text>
            </TouchableOpacity>
          </View>
        </View>
      </View>

      {/* 4. Verification Result Bottom Sheet */}
      <ScanResultSheet
        visible={isResultModalOpen || Boolean(customRejection)}
        onClose={handleDismissResult}
        result={formattedResult}
        loading={checkingIn}
        onPrimaryAction={handleDismissResult}
        primaryActionLabel="Confirm Facility Entry"
        onSecondaryAction={handleDismissResult}
        secondaryActionLabel="Scan Next Ticket"
      />

      {/* 5. Today's Scan History Bottom Sheet */}
      <BottomSheet
        visible={isHistorySheetOpen}
        onClose={() => setIsHistorySheetOpen(false)}
        title="Today's Amenity Check-In Logs"
      >
        <View className="gap-3 pb-4">
          {recentScans && recentScans.length > 0 ? (
            recentScans.slice(0, 10).map((scan: any, idx: number) => {
              const isExit = scan.scanType === 'Exit';
              const scanTimeFormatted = scan.scanTime
                ? new Date(scan.scanTime).toLocaleTimeString([], {
                    hour: '2-digit',
                    minute: '2-digit',
                  })
                : '-';

              return (
                <ListCard
                  key={scan._id || idx}
                  title={scan.amenityName || 'Amenity Access'}
                  subtitle={`${scan.residentName || 'Resident'} • ${scanTimeFormatted}`}
                  leftIcon={isExit ? 'DoorClosed' : 'DoorOpen'}
                  status={{
                    label: scan.scanType || 'ENTRY',
                    variant: isExit ? 'info' : 'success',
                  }}
                />
              );
            })
          ) : (
            <EmptyState
              icon={History}
              title="No Scan History Recorded"
              description="Amenity attendance logs for today will appear here after passes are verified."
            />
          )}
        </View>
      </BottomSheet>
    </View>
  );
}
