export const TIMEZONE_OPTIONS = [
  { label: 'UTC (Coordinated Universal Time)', value: 'UTC' },
  { label: 'Midway Island, Samoa (SST)', value: 'Pacific/Midway' },
  { label: 'Hawaii (HST)', value: 'Pacific/Honolulu' },
  { label: 'Alaska (AKDT)', value: 'America/Anchorage' },
  { label: 'Pacific Time (US & Canada)', value: 'America/Los_Angeles' },
  { label: 'Mountain Time (US & Canada)', value: 'America/Denver' },
  { label: 'Central Time (US & Canada)', value: 'America/Chicago' },
  { label: 'Eastern Time (US & Canada)', value: 'America/New_York' },
  { label: 'Caracas, La Paz', value: 'America/Caracas' },
  { label: 'Atlantic Time (Canada)', value: 'America/Halifax' },
  { label: 'Newfoundland', value: 'America/St_Johns' },
  { label: 'Brasilia', value: 'America/Sao_Paulo' },
  { label: 'Buenos Aires, Georgetown', value: 'America/Argentina/Buenos_Aires' },
  { label: 'Mid-Atlantic', value: 'Atlantic/South_Georgia' },
  { label: 'Azores', value: 'Atlantic/Azores' },
  { label: 'London, Edinburgh, Dublin, Lisbon (GMT/BST)', value: 'Europe/London' },
  { label: 'Monrovia, Reykjavik', value: 'Africa/Monrovia' },
  { label: 'Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna', value: 'Europe/Berlin' },
  { label: 'Belgrade, Bratislava, Budapest, Ljubljana, Prague', value: 'Europe/Prague' },
  { label: 'Brussels, Copenhagen, Madrid, Paris', value: 'Europe/Paris' },
  { label: 'Sarajevo, Skopje, Warsaw, Zagreb', value: 'Europe/Warsaw' },
  { label: 'West Central Africa', value: 'Africa/Lagos' },
  { label: 'Athens, Bucharest, Istanbul', value: 'Europe/Athens' },
  { label: 'Cairo', value: 'Africa/Cairo' },
  { label: 'Harare, Pretoria', value: 'Africa/Johannesburg' },
  { label: 'Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius', value: 'Europe/Helsinki' },
  { label: 'Jerusalem', value: 'Asia/Jerusalem' },
  { label: 'Baghdad', value: 'Asia/Baghdad' },
  { label: 'Kuwait, Riyadh', value: 'Asia/Riyadh' },
  { label: 'Moscow, St. Petersburg, Volgograd', value: 'Europe/Moscow' },
  { label: 'Nairobi', value: 'Africa/Nairobi' },
  { label: 'Tehran', value: 'Asia/Tehran' },
  { label: 'Abu Dhabi, Muscat (GST)', value: 'Asia/Dubai' },
  { label: 'Baku', value: 'Asia/Baku' },
  { label: 'Kabul', value: 'Asia/Kabul' },
  { label: 'Ekaterinburg', value: 'Asia/Yekaterinburg' },
  { label: 'Islamabad, Karachi, Tashkent', value: 'Asia/Karachi' },
  { label: 'Chennai, Kolkata, Mumbai, New Delhi (IST)', value: 'Asia/Kolkata' },
  { label: 'Kathmandu', value: 'Asia/Kathmandu' },
  { label: 'Astana, Dhaka', value: 'Asia/Dhaka' },
  { label: 'Sri Jayawardenepura', value: 'Asia/Colombo' },
  { label: 'Almaty, Novosibirsk', value: 'Asia/Almaty' },
  { label: 'Yangon (Rangoon)', value: 'Asia/Yangon' },
  { label: 'Bangkok, Hanoi, Jakarta', value: 'Asia/Bangkok' },
  { label: 'Krasnoyarsk', value: 'Asia/Krasnoyarsk' },
  { label: 'Beijing, Chongqing, Hong Kong, Urumqi', value: 'Asia/Shanghai' },
  { label: 'Kuala Lumpur, Singapore', value: 'Asia/Singapore' },
  { label: 'Taipei', value: 'Asia/Taipei' },
  { label: 'Perth', value: 'Australia/Perth' },
  { label: 'Irkutsk, Ulaanbaatar', value: 'Asia/Irkutsk' },
  { label: 'Seoul', value: 'Asia/Seoul' },
  { label: 'Osaka, Sapporo, Tokyo', value: 'Asia/Tokyo' },
  { label: 'Yakutsk', value: 'Asia/Yakutsk' },
  { label: 'Darwin', value: 'Australia/Darwin' },
  { label: 'Adelaide', value: 'Australia/Adelaide' },
  { label: 'Canberra, Melbourne, Sydney', value: 'Australia/Sydney' },
  { label: 'Brisbane', value: 'Australia/Brisbane' },
  { label: 'Hobart', value: 'Australia/Hobart' },
  { label: 'Vladivostok', value: 'Asia/Vladivostok' },
  { label: 'Guam, Port Moresby', value: 'Pacific/Guam' },
  { label: 'Magadan, Solomon Is., New Caledonia', value: 'Asia/Magadan' },
  { label: 'Auckland, Wellington', value: 'Pacific/Auckland' },
  { label: 'Fiji, Kamchatka, Marshall Is.', value: 'Pacific/Fiji' },
  { label: "Nuku'alofa", value: 'Pacific/Tongatapu' }
];

export const LANGUAGE_OPTIONS = [
  { label: 'English (US)', value: 'en-US' },
  { label: 'English (UK)', value: 'en-GB' },
  { label: 'Arabic', value: 'ar-SA' },
  { label: 'French', value: 'fr-FR' },
  { label: 'Spanish', value: 'es-ES' },
  { label: 'German', value: 'de-DE' },
  { label: 'Italian', value: 'it-IT' },
  { label: 'Portuguese (Brazil)', value: 'pt-BR' },
  { label: 'Portuguese (Portugal)', value: 'pt-PT' },
  { label: 'Russian', value: 'ru-RU' },
  { label: 'Chinese (Simplified)', value: 'zh-CN' },
  { label: 'Chinese (Traditional)', value: 'zh-TW' },
  { label: 'Japanese', value: 'ja-JP' },
  { label: 'Korean', value: 'ko-KR' },
  { label: 'Hindi', value: 'hi-IN' },
  { label: 'Bengali', value: 'bn-IN' },
  { label: 'Urdu', value: 'ur-PK' },
  { label: 'Turkish', value: 'tr-TR' },
  { label: 'Dutch', value: 'nl-NL' },
  { label: 'Vietnamese', value: 'vi-VN' },
  { label: 'Thai', value: 'th-TH' },
  { label: 'Indonesian', value: 'id-ID' },
  { label: 'Malay', value: 'ms-MY' },
  { label: 'Filipino (Tagalog)', value: 'fil-PH' },
  { label: 'Polish', value: 'pl-PL' },
  { label: 'Swedish', value: 'sv-SE' },
  { label: 'Danish', value: 'da-DK' },
  { label: 'Norwegian', value: 'no-NO' },
  { label: 'Finnish', value: 'fi-FI' },
  { label: 'Greek', value: 'el-GR' },
  { label: 'Hebrew', value: 'he-IL' },
  { label: 'Swahili', value: 'sw-KE' },
  { label: 'Amharic', value: 'am-ET' },
  { label: 'Yoruba', value: 'yo-NG' },
  { label: 'Zulu', value: 'zu-ZA' },
  { label: 'Afrikaans', value: 'af-ZA' },
  { label: 'Hausa', value: 'ha-NG' }
];
